# Generated by Django 6.0 on 2026-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
