# Generated by Django 6.0 on 2026-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s1app', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='s1app.author'),
        ),
    ]
